### ISSUE TITLE
deps are really outdated

### ISSUE THREAD

**Issue by lucidNTR** [jeffbski/wait-on#11]
please update the deps

**Comment by jeffbski** [comment]
I updated these in two chunks:

First updated everything except joi (which requires Node.js v4+) and released that as v1.5.4, this will be the last planned version usable by Node.js v0.10 and v0.12
https://github.com/jeffbski/wait-on/releases/tag/v1.5.4

Then updated joi and released as v2.0.0 requiring Node.js v4+
https://github.com/jeffbski/wait-on/releases/tag/v2.0.0

Both were published to npm.

**Comment by lucidNTR** [comment]
cool thanks 👍
