### ISSUE TITLE
Axios Vulnerability

### ISSUE THREAD

**Issue by sufcboy** [jeffbski/wait-on#111]
This library is appearing on the vulnerability listing as **Axios** requires the version **>=1.14.7** of **follow-redirects**.

Axios have updated this in master. When they make the next version available this dependency should be updated.

Thanks!

**Comment by jeffbski** [comment]
Sorry for the delay. I just merged the PR to resolve this.

**Comment by jeffbski** [comment]
Published v6.0.1
