### ISSUE TITLE
1.5.4 does not seem to be on npm

### ISSUE THREAD

**Issue by lukebatchelor** [jeffbski/wait-on#12]
Hi there,

I see in the releases tab that the last compatible release for node 0.12 was 1.5.4, but I cant seem to see it on npm. Has this not been published? Not a huge problem for us, I'll roll back to 1.5.3 for now.

Thanks!

**Comment by jeffbski** [comment]
Sorry about that, somehow it must have not gotten published to npm. It is up there now.

**Comment by lukebatchelor** [comment]
Wow... You literally replied, fixed and closed this faster than I could re-run our build!

Thanks!!

**Comment by jeffbski** [comment]
Fantastic!
