### ISSUE TITLE
Updating Axios - Snyk security vulnerability

### ISSUE THREAD

**Issue by seanputera** [jeffbski/wait-on#143]
Hello, this library is appearing on the vulnerability listing from [Snyk](https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459). This library is a dependency from [start-server-and-test](https://github.com/bahmutov/start-server-and-test), and it requires Axios to be the latest version `1.6.0`.

Axios release 1.6.0: https://github.com/axios/axios/releases/tag/v1.6.0

Thank you.

**Comment by AndrewMax** [comment]
[This PR should fix it](https://github.com/jeffbski/wait-on/pull/147), please review. Thanks!

**Comment by seanputera** [comment]
Merged https://github.com/jeffbski/wait-on/pull/147. Thank you @AndrewMax
