### ISSUE TITLE
wait-on not working with http-get://localhost:3000 on Vite 5's preview command

### ISSUE THREAD

**Issue by FezVrasta** [jeffbski/wait-on#150]
It used to work with Vite 4, but with Vite 5 it times out even though the web server is reachable.

**Comment by raymondjacobson** [comment]
@FezVrasta any alternatives?

**Comment by raymondjacobson** [comment]
https://github.com/jeffbski/wait-on/issues/78

**Comment by janbrasna** [comment]
@FezVrasta This was an issue with Vite 5 itself:
- https://github.com/vitejs/vite/issues/9520 so update to v5.0.2+ and this should resolve itself.
- https://github.com/jeffbski/wait-on/issues/78#issuecomment-1168140765 shows another way waiting just for the port be available `wait-on tcp:3000`
