### ISSUE TITLE
wait-on does not seems to execute next command

### ISSUE THREAD

**Issue by Asargiotakis** [jeffbski/wait-on#18]
Hello,  i don't know if i use the wait-on command wrong or if it's something else happening.
I would like to execute some commands and when these are done i would like to run the last one, but only when the others are done. More specifically i have an angular project and i describe in package.json some commands to execute in parallel ( 1) i run a jar to respond in my API calls , 2) ng serve ,3) start the selenium server to run some tests) and when they are finished i would like to run my protractor tests. 
so in package.json i do:
```
{
    "start": "ng serve",
    "java": "java -jar someJar.jar",
    "w1": "webdriver-manager update --ignore_ssl --proxy http://*****.com:8080 && webdriver-manager start",
    "w2": "protractor",
    "k3": "wait-on -l localhost:4444/wd/hub/ && w2",
    "k1": "run-p java start w1 k3"
}
```
but "k3" command seems not to execute, because protractor creates .json file when tests are done...
Is it something that i do wrong???

**Comment by ifyio** [comment]
@Asargiotakis did you ever resolve this?

**Comment by jeffbski** [comment]
fantastic!
