### ISSUE TITLE
leak when timeout happens

### ISSUE THREAD

**Issue by hossameldeen** [jeffbski/wait-on#24]
### Problem

If you run this code:

```
waitOn({resources: ['a-file-that-will-never-exist'], timeout: 10000, interval: 1000}, err => console.log(err))
```

you'll find that the process doesn't exit.

### Possible Cause

If you add logging, you'll find there're `child next` logs long after the timeout has finished.

```
waitOn({resources: ['a-file-that-will-never-exist'], timeout: 10000, interval: 1000, log: true, verbose: true}, err => console.log(err))
```

Also, by running [wtfnode](https://www.npmjs.com/package/wtfnode), the problem indeed seems to be related to rx:

```
- Timers:
  - (995 ~ 995 ms) schedule @ /usr/src/app/node_modules/rx/dist/rx.js:1349
  - (1000 ~ 1000 ms) schedule @ /usr/src/app/node_modules/rx/dist/rx.js:1349
```

So, probably, it's related to not disposing of `subs` _and/or_ `childSub` in case `timeoutTimer` fires. Unfortunately, not familiar enough with rx's `dispose()` to tell for sure the problem cause & how to solve the problem.

(To try out `wtfnode`, add `var wtf = require('wtfnode'); setTimeout(function() {wtf.dump()}, 60000);` at the beginning of your code).

### Why it didn't show up in tests

The reason this problem didn't show in mocha tests is that mocha v3 it used to ["_automatically kill itself via process.exit() when it thinks it should be done running_"](https://boneskull.com/mocha-v4-nears-release/#mochawontforceexit). The problem will show up if you test with mocha v4 or if you add `--no-exit` to `test` script:

```
    "test": "mocha --no-exit 'test/**/*.mocha.js'"
```

You'll find that `npm test` doesn't exit.

<br/>
Thanks for the awesome package! And sorry I couldn't send in a fix :(

**Comment by pengisgood** [comment]
Can we dispose `subsc` in the `timeoutTimer`? Maybe similar like this:
```
    var subsc = null;
    if (opts.timeout !== Infinity) {
        timeoutTimer = setTimeout(function () {
            log('wait-on(%s) timed out waiting for: %s; exiting with error', process.pid, lastWaitForOutput);

            subsc.dispose();

            cb(new Error('Timeout'))
        }, opts.timeout);
    }
```

**Comment by jeffbski** [comment]
I have a fresh rewrite of the wait-on implementation which I think is simpler and hopefully will remove some of the race conditions that were possible.

You can try out the new version 4.0.0-rc.0 by

npm i wait-on@next
Let me know if this fixes the issues you were having.

Thanks!
