### ISSUE TITLE
For some reason wait-on is pretty slow when checking for ports

### ISSUE THREAD

**Issue by aalexgabi** [jeffbski/wait-on#27]
```
# time wait-on tcp:80 tcp:3306

real	0m1.797s
user	0m0.290s
sys	0m0.053s
```
And wait-port for comparison:
```
# time (wait-port 80 && wait-port 3306)
Waiting for localhost:3306.
Connected!
Waiting for localhost:80.
Connected!

real	0m0.173s
user	0m0.147s
sys	0m0.027s
```

**Comment by jeffbski** [comment]
The configurable delay, interval, and window can be used to tune to your liking. It really depends on what you are monitoring, if you are monitoring whether files have changed in a build then a longer interval is appropriate, if you simply want to check whether a server port is listening then you can get away with a quicker interval.

**Comment by aalexgabi** [comment]
@jeffbski I tried with 0 interval and 0 delay while Mysql is already listening:
```
root@c00e4b01cf61:/var/www# time wait-on -v -d 0 -i 0 tcp:3306
child next [ { 'tcp:3306': 1 } ]
child complete
child next []
stabilized

real	0m1.770s
user	0m1.067s
sys	0m0.383s

```

It's still very slow.
