### ISSUE TITLE
Bug: Dropped support for Node.js 4 in a patch release

### ISSUE THREAD

**Issue by watson** [jeffbski/wait-on#28]
I just noticed that you dropped support for Node.js 4 in a patch release. While we all desperately want to get rid of Node 4, this unfortunately means that a lot of upstream dependents that still run their CI on Node 4 now have failing tests because they depend on this module using `^2.0.0`.

Even though Node 4 is now EOL, it would be more smooth if breaking changes like this wasn't introduced in a minor or patch version 😅

Can I suggest that you roll back your new release and instead release it as a major?

**Comment by jeffbski** [comment]
@watson Thanks for bringing this to my attention. I'll revert the change and make it in a new major version.

**Comment by jeffbski** [comment]
@watson I have reverted the changes that dropped node 4 support and released as 2.1.2

I have moved the breaking changes to 3.0.0 which drops support for node 4

**Comment by watson** [comment]
Awesome, thanks for understanding 😃

**Comment by jeffbski** [comment]
I'm glad you brought it to my attention. It was easy enough to just make that a major release and avoid the problem. I know now for the future that this is what I should do. Thanks.
