### ISSUE TITLE
crash when waiting on file in not (yet) existing directory

### ISSUE THREAD

**Issue by caligo-erik** [jeffbski/wait-on#39]
wait-on crashes when waiting for a file and a part of the path doesn't exist yet, e.g. `wait-on output/something.txt`.

A workaround (e.g. `mkdir output` ) is not straight-forward when dealing with nested resources, e.g. `wait-on output/client/clientv1.zip` and similar.

**Comment by CesarManriqueH** [comment]
I think you could pass `--parent` to mkdir and create the whole directory hierarchy. In your case it would be `mkdir --parent output/client` or `mkdir -p output/client` for short.

**Comment by caligo-erik** [comment]
> I think you could pass `--parent` to mkdir and create the whole directory hierarchy. In your case it would be `mkdir --parent output/client` or `mkdir -p output/client` for short.

Thanks for the hint.

**Comment by jeffbski** [comment]
Check the latest rc, it seems to handle this fine. I have now added tests to check for this as well. 

I have a fresh rewrite of the wait-on implementation which I think is simpler and hopefully will remove some of the race conditions that were possible.

You can try out the new version 4.0.0-rc.0 by

npm i wait-on@next
Let me know if this fixes the issues you were having.

Thanks!

**Comment by jeffbski** [comment]
Released 4.0.0 which hopefully will solve these issues. Let me know if you have further problems.

https://github.com/jeffbski/wait-on/releases/tag/v4.0.0
