### ISSUE TITLE
Missing v3.3.0 tag / changelog?

### ISSUE THREAD

**Issue by valscion** [jeffbski/wait-on#41]
Hi there,

I noticed you've bumped the version to v3.3.0 in e00b1a166ae58ba05bd62e6fdc43f8202d4343f3. However, it seems that no git tag for v3.3.0 was ever pushed here? I couldn't find release notes or tags in https://github.com/jeffbski/wait-on/releases for v3.3.0

These seem to be the changes done between v3.2.0 and v3.3.0: https://github.com/jeffbski/wait-on/compare/v3.2.0...e00b1a166ae58ba05bd62e6fdc43f8202d4343f3

If the changelog were to look similar to [v3.2.0 release](https://github.com/jeffbski/wait-on/releases/tag/v3.2.0), would something like this be OK?

---

* Added `--httpTimeout` option
  
  ```
  --httpTimeout

    Maximum time in ms to wait for an HTTP HEAD/GET request, default 0
    which results in using the OS default
  ```

* Upgraded dependencies: https://github.com/jeffbski/wait-on/pull/38, thanks [@matijagaspar](https://github.com/matijagaspar)

* Require Node Version +8.9.0: https://github.com/jeffbski/wait-on/pull/33

**Comment by jeffbski** [comment]
Thanks for mentioning it. I guess I never pushed up the tag from local. It is up there now. Yes, your release notes look good. I have updated them now.

https://github.com/jeffbski/wait-on/releases/tag/v3.3.0

**Comment by valscion** [comment]
Thanks! Thank you for `wait-on`, it's a useful tool for us ☺️
