### ISSUE TITLE
Dropped support for Node v6 in minor release

### ISSUE THREAD

**Issue by perry-mitchell** [jeffbski/wait-on#44]
Hi! I've been using `wait-on` in [webdav-client](https://github.com/perry-mitchell/webdav-client), which still supports Node 6, and I see that in the latest version of your library Node 6 no longer works.. Was this intentional? Seems strange that a minor release would drop support for a node version.

Definitely understand not wanting to support v6 as it's out of support, but it'd be interesting to know what your plans are here - whether or not I should switch to another library or just lock the version.

Thanks!

**Comment by jeffbski** [comment]
Sorry I should have bumped the major version when removing node v6. I guess easiest thing to do while you still need node v6 is to lock the version.  I will be more careful going forward and do my best to follow semver with anything breaking being a major bump.

Thanks for keeping me honest.

**Comment by jeffbski** [comment]
I mentioned it in the release notes as well.
