### ISSUE TITLE
Deprecated version of core-js

### ISSUE THREAD

**Issue by DamienCassou** [jeffbski/wait-on#47]
wait-on seems to depend on an old version of core-js. Yarn warns me:

> core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

**Comment by jeffbski** [comment]
Check out the new RC, I have upgraded everything.

I have a fresh rewrite of the wait-on implementation which I think is simpler and hopefully will remove some of the race conditions that were possible.

You can try out the new version 4.0.0-rc.0 by

npm i wait-on@next

Thanks!

**Comment by DamienCassou** [comment]
Thank you for your work. I won't be able to test because my code doesn't have any dependency to `wait-on` anymore. It was an indirect dependency and I forgot which package was depending on `wait-on`.

**Comment by jeffbski** [comment]
https://github.com/jeffbski/wait-on/releases/tag/v4.0.0
