### ISSUE TITLE
Please upgrade core-js

### ISSUE THREAD

**Issue by ArtashMardoyan** [jeffbski/wait-on#48]
warning wait-on > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

**Comment by jeffbski** [comment]
Check the latest rc, I have upgraded everything. 

I have a fresh rewrite of the wait-on implementation which I think is simpler and hopefully will remove some of the race conditions that were possible.

You can try out the new version 4.0.0-rc.0 by

npm i wait-on@next
Let me know if this fixes the issues you were having.

Thanks!

**Comment by jeffbski** [comment]
https://github.com/jeffbski/wait-on/releases/tag/v4.0.0
