### ISSUE TITLE
Dependency on Deprecated node "request" library

### ISSUE THREAD

**Issue by lucasassisrosa** [jeffbski/wait-on#53]
This lib has a dependency on node's request library, which is recently deprecated. Not sure if possible but I think it'd be nice to use another lib

**Comment by solsglasses** [comment]
Hey @jeffbski, love your npm package. The deprecation of `request` now blocks anyone that wants to responsibly use `wait-on` in a production app.

Here is a list of possible alternatives:

https://github.com/request/request/issues/3143

**Comment by jeffbski** [comment]
Thanks to both of you for raising the issue. I will swap it out. I should have that done this weekend.

**Comment by jeffbski** [comment]
@lucasassisrosa @solsglasses If you have a chance please try out the new prerelease version of wait-on to see if it works as expected. I switched to axios from request in the 5.0.0-rc.0 release.

You can install using `npm i wait-on@next`

There were a few breaking changes in the options which are listed here: https://github.com/jeffbski/wait-on/releases/tag/v5.0.0-rc.0

Let me know how it goes.

**Comment by solsglasses** [comment]
I'm a CLI customer myself, so I did some basic checks based off your README:

> ✅wait-on http://localhost:8000/foo && NEXT_CMD # wait for http 2XX HEAD
> ✅wait-on https://myserver/foo && NEXT_CMD # wait for https 2XX HEAD
> ✅wait-on http-get://localhost:8000/foo && NEXT_CMD # wait for http 2XX GET
> ✅wait-on https-get://myserver/foo && NEXT_CMD # wait for https 2XX GET

I don't know how to test these

> ✅wait-on http://unix:/var/SOCKPATH:/a/foo # wait for http HEAD on domain socket
> ✅wait-on http-get://unix:/var/SOCKPATH:/a/foo # wait for http GET on domain socket

I also tried things that I knew would fail (wrong ports, non-SSL links, Basic Auth, etc.), to see how `wait-on` would respond, and it handled everything gracefully.

**Comment by jeffbski** [comment]
I have published 5.0.0, thanks for all the support.
