### ISSUE TITLE
[Feature Request] Support for other HTTP methods

### ISSUE THREAD

**Issue by jchook** [jeffbski/wait-on#57]
Currently it seems `wait-on` only supports the HTTP `GET` and `HEAD` methods.

Perhaps we could also have an `http-post://` scheme with, for example, a `data` option?

**Comment by jeffbski** [comment]
yes, I guess that would be reasonable. Just needs a little thinking about how we would specify the payload.

**Comment by rcalabro** [comment]
could be a parameter like `curl` for example:
` -d '{"key1":"value1", "key2":"value2"}' `

**Comment by jeffbski** [comment]
Yeah, only issue with that is that you can provide many different URLs in one call or execution, so if we needed to provide different data for each URL then we'd need a way to distinguish that.

Maybe we would append something to the URL to accommodate that. I'll give it some more thought.

**Comment by jchook** [comment]
In terms of command line options, you borrow from, e.g. `ffmpeg`, `tar`, etc, where the order of the arguments matters.

```
wait-on -d data1 url1 -d data2 url2
wait-on -d data1 -d data2 url1 url2
...
```

Or you could perhaps use the "fragment" of the URL for meta info, e.g.

```
wait-on http-post://host/path?query#data=url-encoded-data1
```

**Comment by jeffbski** [comment]
Yes, agreed @jchook. Those are the kinds of options we could take. I just want it to be as simple and clean as possible. 

Another idea is what about allowing it separated by space in the argument with the URL? So basically whatever comes after the URL is JSON parsed as the data to post.

```shell
wait-on 'http-post://foo/bar {"key": "value", "key2":"key":"value2"}'
```

That would allow different values easily without any special ordering of params.

```shell
wait-on 'http-post://foo/bar {"key": "value", "key2":"key":"value2"}' 'http-post://cat/ {"dog": "value3", "egg":"key":"value4"}'
```

**Comment by jchook** [comment]
I'll add too, though I think others may find it useful in the future, I personally no longer need this feature. 

At first I made a node-only clone, [rewait](https://github.com/jchook/rewait), then the HTTP POST requirement went away entirely, so I switched back to wait-on.

If it's too much of a can of worms, you could close the issue until there is evidence of demand. Not sure if @rcalabro is hoping for this feature.

Another thought is to only allow the feature when used via the node API.

**Comment by jeffbski** [comment]
Yeah, it kind of makes sense to maybe only do this from node API. Anything that makes the CLI get too clunky should probably go to the API or maybe using a config file.

I'll see what @rcalabro thinks.

**Comment by rcalabro** [comment]
Not really. I use to wait on files mostly...

I agree with closing this issue, there is a lot of corner cases to think about ...

**Comment by jeffbski** [comment]
ok, we'll close it for now. Thanks for the discussions.
