### ISSUE TITLE
Allow auth.user to be empty

### ISSUE THREAD

**Issue by xXKeyleXx** [jeffbski/wait-on#59]
Please allow the user in the auth parameter to be an empty string.

The VLC HTTP interface for example needs the user to be empty.

```
(node:5921) UnhandledPromiseRejectionWarning: ValidationError: "auth.user" is not allowed to be empty
```

**Comment by jeffbski** [comment]
I just released 5.0.0 and tested that it does not require username to be populated. 

In v5.0.0, use username and password rather than user and pass.
