### ISSUE TITLE
Suggestion: Timeout error message should include remaining resources in the message

### ISSUE THREAD

**Issue by jmealo** [jeffbski/wait-on#72]
It would be great if the error returned when a timeout occurs included the output of `determineRemainingResources` in the message (or as a property). If you'd like I can do a PR for either/or.

Thanks,
Jeff

**Comment by jeffbski-rga** [comment]
@jmealo yes, that is a good idea, that way it goes back with the error. Currently if you enable logging you will see a log message with the remaining resources, but it would be nice to have it as part of the error too. 

So yes, if you want to create a PR that would be wonderful. Thanks!

**Comment by jmealo** [comment]
@jeffbski-rga: Thanks for the quick response: #73 is a PR implementing this. I took a few stabs at this to keep the current behavior unchanged. Presently, stack traces are output for non-timeout errors (which is desirable). Stack traces for timeouts are not helpful as they point to some rxjs internals, so I'm omitting them with a ternary to match current behavior. I can make it a conditional branch like it was for clarity's sake if you'd like.

**Comment by jmealo** [comment]
@jeffbski: I tweaked this a bit. I think db03720 matches the coding style/log output better.
